//
//  DbSizeSweep.swift
//  BlazeDBBenchmarks
//
//  BLAZEDB_BENCH_MODE=db_size_sweep — durable insert latency vs preexisting DB row count.
//

import Foundation
import BlazeDBCore

enum DbSizeSweep {
    /// Pre-seed row counts before measuring fresh inserts (standard ~53 B shape).
    static let defaultSeedCounts: [Int] = [
        0, 1_000, 10_000, 50_000, 100_000,
    ]

    struct Row: Codable {
        let seedRowCount: Int
        let measureInserts: Int
        let encodedPayloadBytes: Int
        let recordShape: String
        let dbBytesAfterSeed: Int
        let blazedbAvgMs: Double
        let blazedbP50Ms: Double
        let blazedbP95Ms: Double
        let blazedbP99Ms: Double
        let blazedbOpsPerSec: Double
        let notes: String
    }

    private static func measureInsertCount(forSeed seed: Int) -> Int {
        switch seed {
        case ..<1_000: return 200
        case ..<10_000: return 100
        case ..<50_000: return 50
        default: return 30
        }
    }

    static func run(seedCounts: [Int] = defaultSeedCounts) throws -> [Row] {
        let encoded = BenchPayload.sampleStandardEncodedBytes()
        var rows: [Row] = []
        for seed in seedCounts {
            let n = measureInsertCount(forSeed: seed)
            print("  seed=\(seed) rows, measure=\(n) inserts (encoded≈\(encoded) B)...")

            let tempDir = FileManager.default.temporaryDirectory
                .appendingPathComponent("DbSizeSweep-\(UUID().uuidString)", isDirectory: true)
            try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
            defer { try? FileManager.default.removeItem(at: tempDir) }

            let dbURL = tempDir.appendingPathComponent("size.blazedb")
            let db = try openBenchDB(name: "db-size-sweep", fileURL: dbURL)

            if seed > 0 {
                let batchSize = 500
                var batch: [BlazeDataRecord] = []
                batch.reserveCapacity(batchSize)
                for i in 0..<seed {
                    batch.append(BenchPayload.standardRecord(index: i, dataPrefix: "seed"))
                    if batch.count == batchSize || i == seed - 1 {
                        _ = try db.insertMany(batch)
                        batch.removeAll(keepingCapacity: true)
                    }
                }
                try db.persist()
            }

            let dbBytes = (try? FileManager.default.attributesOfItem(atPath: dbURL.path)[.size] as? NSNumber)?.intValue ?? 0

            var durationsMs: [Double] = []
            durationsMs.reserveCapacity(n)
            let wallStart = Date()
            for i in 0..<n {
                let record = BenchPayload.standardRecord(index: seed + i, dataPrefix: "measure")
                let opStart = benchMonotonicNowMs()
                _ = try db.insert(record)
                durationsMs.append(benchMonotonicNowMs() - opStart)
            }
            try db.persist()
            try db.close()
            let wallSec = Date().timeIntervalSince(wallStart)
            let stats = summarizeMs(durationsMs)
            rows.append(
                Row(
                    seedRowCount: seed,
                    measureInserts: n,
                    encodedPayloadBytes: encoded,
                    recordShape: BenchPayload.standardShapeDescription,
                    dbBytesAfterSeed: dbBytes,
                    blazedbAvgMs: stats?.avgMs ?? 0,
                    blazedbP50Ms: stats?.p50Ms ?? 0,
                    blazedbP95Ms: stats?.p95Ms ?? 0,
                    blazedbP99Ms: stats?.p99Ms ?? 0,
                    blazedbOpsPerSec: wallSec > 0 ? Double(n) / wallSec : 0,
                    notes: "Standard-shape insert() after seed; investigates 1K→10K latency degradation"
                )
            )
        }
        return rows
    }

    static func markdownReport(_ rows: [Row]) -> String {
        var md = """
        # Write latency vs database size

        _Generated by `BLAZEDB_BENCH_MODE=db_size_sweep`._

        Standard-shape durable `insert()` after seeding N rows. Use this to check whether latency grows
        with DB size (beyond a fixed fsync). See `Docs/Benchmarks/HONEST_PERFORMANCE.md`.

        | Seed rows | DB bytes after seed | Encoded B | N measure | ops/s | avg ms | p50 | p95 | p99 |
        |---:|---:|---:|---:|---:|---:|---:|---:|---:|

        """
        for r in rows {
            md += "| \(r.seedRowCount) | \(r.dbBytesAfterSeed) | \(r.encodedPayloadBytes) | \(r.measureInserts) | "
            md += String(format: "%.1f | %.3f | %.3f | %.3f | %.3f |\n",
                         r.blazedbOpsPerSec, r.blazedbAvgMs, r.blazedbP50Ms, r.blazedbP95Ms, r.blazedbP99Ms)
        }
        md += "\n"
        return md
    }
}
